### ISSUE TITLE
Reset test ability

### ISSUE THREAD

**Issue by balthazar** [SIGSEV/KeyCode#12]
Not sure because it might conflict with system commands, but having something to prevent us from <kbd>Ctrl</kbd> + <kbd>R</kbd> the page manually could be neat.

**Comment by meriadec** [comment]
A non-intrusive way would be to have a reset button after the TypeWriter component, so that you can focus it with a simple & accessible <kbd>Tab</kbd>.

So, <kbd>Tab</kbd>+<kbd>Enter</kbd> to restart. What do you think?

**Comment by balthazar** [comment]
Sounds good to me

**Comment by balthazar** [comment]
I got a few feedbacks that people tend to do <kbd>Tab</kbd> when they are focused on the text, and thus go on the github link (and they didn't even knew you could <kbd>Shift</kbd> + <kbd>Tab</kbd> to go back but that's another thing). I was saying that they should fuck off and learn not to do it because we planned to have this reset button next to the input, but wanted to hear your thoughts too first. Maybe something like a key combinaison wouldn't be so bad? Or having a user-setting for this (in v2?)? Not sure anymore

**Comment by balthazar** [comment]
Don't know where to put this, can you take over @meriadec ?
