### ISSUE TITLE
Harder sanction on skipped words

### ISSUE THREAD

**Issue by meriadec** [SIGSEV/KeyCode#15]
I have the _feeling_ that some users are taking advantage of the ability to skip words, especially when they are long. 😂 

To prevent this behaviour, let's punish any skipped word by a *very hard* malus on the final score (-10 or -15 *by skipped word*).

A skipped word is a word that is validated before typing the right amount of letters OR with more than 3 errors.

**Comment by balthazar** [comment]
Sounds good, could we just disable this for one or two char words? Also I think it might make sense to have the breakdown system first?

**Comment by balthazar** [comment]
Actually, what about giving a _minus_ based on the total number of chars in the skipped word? It would make it instantly unprofitable to skip.

**Comment by meriadec** [comment]
Sounds smart :ok_hand:

Btw, it will require not only to store the skipped words count, but also the skipped words

**Comment by balthazar** [comment]
Since it's not possible to skip words anymore, I believe this should be closed.
