### ISSUE TITLE
Record every keystroke with timestamp

### ISSUE THREAD

**Issue by balthazar** [SIGSEV/KeyCode#16]
This way we could see the replay of previous races of any users, reducing cheat possibilites.

**Comment by meriadec** [comment]
sounds good! also, we should think about a "compressed" way to store them. first, instead of unix timestamps we can start at 0, and store all that in a string. e.g:

```
0|k 120|e 144|y 210|c 251|o 312|d 400|e
```

and we need to think about how to store <kbd>Enter</kbd> and <kbd>Space</kbd>

**Comment by balthazar** [comment]
What I had to change for mongoose to be able to save `.` and `$` for the
valid and wrong keys is to use the from char code rather than the real
char, maybe we can use something similar, and stock the.... KEYCODE!!? Or
would that wouldn't work with different layouts?

**Comment by balthazar** [comment]
What I had to change for mongoose to be able to save `.` and `$` for the valid and wrong keys is to use the char code rather than the real char, maybe we can use something similar, and stock the.... KEYCODE!!? Or would that wouldn't work with different layouts?

**Comment by meriadec** [comment]
Using keycodes (lel) will solve the problem, yep! But I think it's still better to store that serialized in a string rather than in some complex/big object. It could be deserialized easily client side to do some replays!

**Comment by balthazar** [comment]
Yes the serialization part is good, didn't _acknowledged_ that I apologize.
