### ISSUE TITLE
When the URL is directly accessed, the back button does not work

### ISSUE THREAD

**Issue by HT808s** [SIGSEV/KeyCode#21]
The given URL 
https://keycode.sigsev.io/r/beauty-withdrawal-bedfordshire

**Comment by balthazar** [comment]
Good first issue? I would say it's a bit tricky, what do you want to do exactly? Remove the back and just go to home?

**Comment by meriadec** [comment]
don't know. I'm not even sure that it's a good idea to have that "back" button. maybe we can have some sort of ariane string, with "back to language" "all languages"

**Comment by meriadec** [comment]
`All languages > Elm > beauty-withdrawal-bedfordshire`

Also, I'm wondering why we dont use the slugified title as race url

**Comment by meriadec** [comment]
the "good first issue" badge was more for inclusion than for coherence
