### ISSUE TITLE
CoC

### ISSUE THREAD

**Issue by balthazar** [SIGSEV/KeyCode#22]
![screen shot 2017-11-21 at 12 30 35 am](https://user-images.githubusercontent.com/6033345/33062183-3e513ab2-ce53-11e7-8cb7-e3afa1a20504.png)

We need one!

**Comment by meriadec** [comment]
still marked as warning in github insights. bug?

![2017-11-21_376x352](https://user-images.githubusercontent.com/315259/33093157-7b09d8de-cefc-11e7-83a6-b8eb24961550.png)

**Comment by balthazar** [comment]
Yeah we need to report this, we have one I don't get it??? 🤔 🤔 🤔 🤔

**Comment by balthazar** [comment]
Ah it's working now! Must be a little cron!!

**Comment by meriadec** [comment]
Seems that it's again in yellow... strange 🤔

**Comment by balthazar** [comment]
We should forward this to the staff instead of reopening this issue.
