### ISSUE TITLE
Achievements

### ISSUE THREAD

**Issue by balthazar** [SIGSEV/KeyCode#36]
These are some ideas and up to further discussions / additions.

Generally, it could be cool to allow for these to be extensible, eg: do it 5 times, 10, 25, 50..

- [x] Racer (score 80+)
- [x] Mr. Perfect (no typo, score 70+)
- [x] God (no typo - no retry, score 70+)
- [x] Galvanizer (first of a text with 100+ runs & 10+ users)
- [ ] Architect (accumulate stars on authored texts)
- [ ] Supporter (payed for a month of premium)

**Comment by meriadec** [comment]
particulary liking the "Supporter" one
