### ISSUE TITLE
Website not accessible

### ISSUE THREAD

**Issue by Kerumen** [SIGSEV/KeyCode#43]
It looks like there is a certificate error:

<img width="1185" alt="screen shot 2018-10-31 at 11 49 33" src="https://user-images.githubusercontent.com/5436545/47783467-144c8680-dd03-11e8-8e0e-eb9f75fb20a6.png">

**Comment by meriadec** [comment]
Thanks for investigating ! :rocket: :rocket: :mag: Amazing !

But it's not an issue because you can run it locally :) WDYT @balthazar ?

nb: I've trouble to access https://keru.io, is there something wrong with your certificate ? :thinking: That's weird..

**Comment by balthazar** [comment]
My access to the zavatta server has been unfortunately revoked/compromised so I cannot investigate further what appears to be a russian hack financed by typeracer to bring keycode down.

As @meriadec said you are always free to build it locally and play with yourself in the spirit of decentralization and individual empowerment!

**Comment by Kerumen** [comment]
Ok
